# Logit-based Factorization Distiller (FTD) Configuration
strategy: FTD
topology:
  type: FTD
  lambda_td: 0.5
  entity_sample_size: 0

bayesian:
  search_space:
    distillation.topology.lambda_td:
      type: float
      low: 0.00001
      high: 1
      log: true
    distillation.topology.entity_sample_size:
      type: categorical
      choices: [128, 256, 512]
