# Generic Teacher Training Template
train_teacher:
  dataset: null

  teacher:
    default: null

  optimization:
    default: optimization/default.yaml
    batch_size: 2048

  runtime:
    default: runtime/default.yaml

  evaluation:
    default: evaluation/default.yaml
    batch_size: 1024
